# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sberTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sberTest
  # Основная библиотека MapKit.
  pod ‘YandexMapKit’, ’~> 3.3’ 
  # Дополнительные модули MapKit.
  # Удалите зависимости если ваше приложение не использует их.
  pod ‘YandexMapKitDirections’, ’~> 3.3’ 
  pod ‘YandexMapKitPlaces’, ’~> 3.3’ 
  pod ‘YandexMapKitSearch’, ’~> 3.3’ 
  pod ‘YandexMapKitTransport’, ’~> 3.3’ 
  
  target 'sberTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sberTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
